BANK_DIR = "data/questions"  # banks 根目录
TIDB_HOST = "gateway01.eu-central-1.prod.aws.tidbcloud.com"
TIDB_PORT = 4000
TIDB_USER = "2b1cKMtrfhzxjYj.root"
TIDB_DATABASE = "github_sample"

LOCK_TTL_SECONDS = 600
QUESTIONS_PER_PAGE = 20

